version: "3.7"
services:
  web:
    image: ${IMAGE:-gitlab-playground-run:latest}
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db/myuser?sslmode=disable
      - FLASK_ENV=development

  test:
    image: ${IMAGE:-gitlab-playground-build:latest}
    command: pipenv run pytest --verbose --capture=no --cov=hello_world --cov-report term-missing
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db/myuser?sslmode=disable
      - DEBUG=True
      - TESTING=True
      - VERSION=unknown
    volumes:
      - ./coverage/:/app/coverage/

  lint:
    image: ${IMAGE:-gitlab-playground-build:latest}
    command: pipenv run flake8 tests/ hello_world/

  cover:
    image: ${IMAGE:-gitlab-playground-build:latest}
    command: pipenv run coverage report --show-missing --fail-under 81
    volumes:
      - ./coverage/:/app/coverage/

  db:
    image: postgres:11
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass

networks:
  default:
    driver: bridge
    # https://medium.com/@sylwit/how-we-spent-a-full-day-figuring-out-a-mtu-issue-with-docker-4d81fdfe2caf
    # Problem would only appear when running curl on an HTTPS (only S) website inside a docker container
    # Only with Typhoon Kubernetes (self-hosted Gitlab on K8s)
    # Check MTU frag with "ping -c 3 -M do -s 1410 google.fr"
    driver_opts:
      com.docker.network.driver.mtu: 1410
